--[[
    "GLUETEXTBUTTON"
        ButtonPushedTextOffset
        ButtonText
        ControlBackdrop
        ControlDisabledBackdrop
        ControlDisabledPushedBackdrop
        ControlMouseOverHighlight
        ControlPushedBackdrop
        ControlShortcutKey
        ControlStyle
        DecorateFileNames
        FrameFont
        Height
        SetPoint
        UseActiveContext
        Width
    "FRAME"
        DecorateFileNames
        FrameFont
        Height
        SetAllPoints
        SetPoint
        TabFocusPush
        UseActiveContext
        Width
    "BACKDROP"
        BackdropBackground
        BackdropBackgroundInsets
        BackdropBackgroundSize
        BackdropBlendAll
        BackdropBottomFile
        BackdropCornerFile
        BackdropCornerFlags
        BackdropCornerSize
        BackdropEdgeFile
        BackdropHalfSides
        BackdropLeftFile
        BackdropMirrored
        BackdropRightFile
        BackdropTileBackground
        BackdropTopFile
        DecorateFileNames
        Height
        Width
    "BUTTON"
        ControlBackdrop
        ControlMouseOverHighlight
        ControlStyle
        Height
        Width
    "TEXT"
        DecorateFileNames
        FontColor
        FontDisabledColor
        FontFlags
        FontHighlightColor
        FontJustificationH
        FontJustificationOffset
        FontJustificationV
        FontShadowColor
        FontShadowOffset
        FrameFont
    "POPUPMENU"
        ControlBackdrop
        ControlDisabledBackdrop
        ControlPushedBackdrop
        Height
        PopupArrowFrame
        PopupButtonInset
        PopupMenuFrame
        PopupTitleFrame
        Width
    "SLIDER"
        ControlBackdrop
        ControlDisabledBackdrop
        Height
        SliderLayoutHorizontal
        SliderThumbButtonFrame
        Width
    "TEXTAREA"
        ControlBackdrop
        TextAreaInset
        TextAreaLineGap
        TextAreaLineHeight
        TextAreaScrollBar
    "CHATDISPLAY"
        ChatDisplayBorderSize
        ChatDisplayLineHeight
        DecorateFileNames
        FrameFont
    "SIMPLEBUTTON"
        ButtonPushedTextOffset
        DecorateFileNames
        DisabledTexture
        Height
        NormalTexture
        PushedTexture
        UseHighlight
        Width
    "EDITBOX"
        ControlBackdrop
        EditBorderSize
        EditCursorColor
        Height
    "TEXTBUTTON"
        ButtonPushedTextOffset
        ButtonText
        ControlBackdrop
        ControlDisabledBackdrop
        ControlFocusHighlight
        ControlMouseOverHighlight
        ControlPushedBackdrop
        ControlStyle
        DecorateFileNames
        FrameFont
        Height
        Width
    "CHECKBOX"
        CheckBoxCheckHighlight
        CheckBoxDisabledCheckHighlight
        ControlBackdrop
        ControlDisabledBackdrop
        ControlPushedBackdrop
        Height
        Width
    "DIALOG"
        DecorateFileNames
        DialogBackdrop
        FrameFont
        Height
        UseActiveContext
        Width
    "LISTBOX"
        ControlBackdrop
        ListBoxBorder
        ListBoxScrollBar
    "HIGHLIGHT"
        DecorateFileNames
        HighlightAlphaFile
        HighlightAlphaMode
        HighlightType
    "GLUEBUTTON"
        ControlBackdrop
        ControlDisabledBackdrop
        ControlDisabledPushedBackdrop
        ControlFocusHighlight
        ControlMouseOverHighlight
        ControlPushedBackdrop
        ControlStyle
        Height
        Width
    "GLUECHECKBOX"
        CheckBoxCheckHighlight
        CheckBoxDisabledCheckHighlight
        ControlBackdrop
        ControlDisabledBackdrop
        ControlMouseOverHighlight
        ControlPushedBackdrop
        ControlStyle
        Height
        Width
    "SCROLLBAR"
        ControlBackdrop
        ScrollBarDecButtonFrame
        ScrollBarIncButtonFrame
        SetPoint
        SliderLayoutVertical
        SliderThumbButtonFrame
        Width
    "CONTROL"
        ControlBackdrop
        Height
        UseActiveContext
        Width
    "MENU"
        ControlBackdrop
        DecorateFileNames
        FrameFont
        Height
        MenuBorder
        MenuItemHeight
        MenuTextHighlightColor
    "SIMPLEFRAME"
        DecorateFileNames
        Height
        SetAllPoints
        UseActiveContext
        Width
]]

compiletime(function()
    fdf = fdf or {}

    local toc = {
        "ui\\FrameDef\\Glue\\StandardTemplates.fdf",
        "UI\\FrameDef\\Glue\\BattleNetTemplates.fdf",
        "ui\\FrameDef\\UI\\EscMenuTemplates.fdf",
        "war3mapImported/custom.fdf",
        ""
    }

    currentMap:addFileString("war3mapImported/custom.toc", table.concat(toc, "\r\n"))
    currentMap:addFileString("war3mapImported/custom.fdf", fs.readFile("import/custom.fdf"))
end)

event.registerOnce(function()
    print("TOC Loaded: ", BlzLoadTOCFile("war3mapImported/custom.toc"))
end)